/* last version */
SELECT
  Date,Volume, Open, High, Low, AdjClose,
  ROUND(AVG(AdjClose) OVER (ORDER BY Date ROWS BETWEEN 5 following AND 5 following), 6) AS CloseIn5,
  ROUND( (AdjClose-AVG(AdjClose) OVER (ORDER BY Date ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) ) / AdjClose, 6 ) AS Mva5DistPc,
  ROUND( (AVG(AdjClose) OVER (ORDER BY Date ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) -AVG(AdjClose) OVER (ORDER BY Date ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING)) / AVG(AdjClose) OVER (ORDER BY Date ROWS BETWEEN 4 PRECEDING AND CURRENT ROW), 6) AS Mva5DeltaPc,
FROM
  `finseries-poc.quotes.quotes-history`
LIMIT
  100

/* workbench */
SELECT
  Date,
  AdjClose,
  ROUND( (AdjClose-AVG(AdjClose) OVER (ORDER BY Date ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) ) / AdjClose , 6 ) AS Mva5DistPc,
  
  ROUND(
      (AVG(AdjClose) OVER (ORDER BY Date ROWS BETWEEN 4 PRECEDING AND CURRENT ROW)
      -AVG(AdjClose) OVER (ORDER BY Date ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING))
      / AVG(AdjClose) OVER (ORDER BY Date ROWS BETWEEN 4 PRECEDING AND CURRENT ROW)
      , 6) AS Mva5DeltaPc,
 FROM
  `finseries-poc.quotes.quotes-history`
LIMIT
  100

/* extracts */
  ROUND(AVG(AdjClose) OVER (ORDER BY Date ROWS BETWEEN 4 PRECEDING AND CURRENT ROW), 6) AS Mva5,
  ROUND(AVG(AdjClose) OVER (ORDER BY Date ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING), 6) AS prevMva5,
  ROUND(AVG(AdjClose) OVER (ORDER BY Date ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) - AVG(AdjClose) OVER (ORDER BY Date ROWS BETWEEN 5 PRECEDING AND 1 PRECEDING), 6) AS Mva5delta,
  ROUND( (AdjClose-AVG(AdjClose) OVER (ORDER BY Date ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) ) / AdjClose , 6 ) AS Mva5DistPc,




